Repository surfstudio/flutter-bottom-inset-observer, pull requests merged in 2023-04, with the labels that each got.

#17 deyew: added pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new pull request

#18 feat: update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, new pull request

#19 fix(SNP-400): Updates build badge route.
  README.md
Labels: bug, new pull request
